export const enum ActionType {
  BLOOD_GLUCOSE = 'BLOOD_GLUCOSE',
  INSULIN = 'INSULIN',
  MEDICATION = 'MEDICATION',
  FOOD = 'FOOD',
  EXERCISE = 'EXERCISE',
  SLEEP = 'SLEEP',
  SYMPTOMS = 'SYMPTOMS',
  WEIGHT = 'WEIGHT',
  HYDRATION = 'HYDRATION',
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
}

export const ACTION_TYPE_VALUES = [
  'BLOOD_GLUCOSE',
  'INSULIN',
  'MEDICATION',
  'FOOD',
  'EXERCISE',
  'SLEEP',
  'SYMPTOMS',
  'WEIGHT',
  'HYDRATION',
  'BLOOD_PRESSURE',
] as const;
